--JULIAN SPINELLI GRUPO29

-- TABLAS

-- Table: GR29_CARAC_EQUIPO
CREATE TABLE GR29_CARAC_EQUIPO (
    id_carac int  NOT NULL,
    modelo varchar(10)  NOT NULL,
    marca varchar(10)  NOT NULL,
    CONSTRAINT PK_GR29_CARAC_EQUIPO PRIMARY KEY (id_carac)
);

-- Table: GR29_CLIENTE
CREATE TABLE GR29_CLIENTE (
    id_persona int  NOT NULL,
    saldo numeric(18,3)  NOT NULL,
    cuit numeric(11,0)  NOT NULL,
    CONSTRAINT PK_GR29_CLIENTE PRIMARY KEY (id_persona)
);

-- Table: GR29_COMPROBANTE
CREATE TABLE GR29_COMPROBANTE (
    id_tcomp int  NOT NULL,
    id_comp bigint  NOT NULL,
    fecha date  NULL,
    comentario varchar(200)  NOT NULL,
    estado varchar(20)  NULL,
    fecha_vencimiento date  NULL,
    importe decimal(18,2)  NOT NULL,
    tipo_comprobante char(1)  NOT NULL,
    CONSTRAINT PK_GR29_COMPROBANTE PRIMARY KEY (id_tcomp,id_comp)
);

-- Table: GR29_COMPROBANTE_CONL
CREATE TABLE GR29_COMPROBANTE_CONL (
    id_tcomp int  NOT NULL,
    id_comp bigint  NOT NULL,
    id_persona int  NOT NULL,
    CONSTRAINT PK_GR29_COMPROBANTE_CONL PRIMARY KEY (id_tcomp,id_comp)
);

-- Table: GR29_COMPROBANTE_SINL
CREATE TABLE GR29_COMPROBANTE_SINL (
    id_turno int  NOT NULL,
    id_tcomp int  NOT NULL,
    id_comp bigint  NOT NULL,
    CONSTRAINT PK_GR29_COMPROBANTE_SNL PRIMARY KEY (id_tcomp,id_comp)
);

-- Table: GR29_COMPROBANTE_SINL_TURNO
CREATE TABLE GR29_COMPROBANTE_SINL_TURNO (
    id_tcomp int  NOT NULL,
    id_comp bigint  NOT NULL,
    id_persona int  NOT NULL,
    id_turno int  NOT NULL,
    CONSTRAINT PK_GR29_COMP_SINL_TURNO PRIMARY KEY (id_tcomp,id_comp,id_persona,id_turno)
);

-- Table: GR29_DIRECCION
CREATE TABLE GR29_DIRECCION (
    id_direccion int  NOT NULL,
    calle varchar(50)  NOT NULL,
    numero int  NOT NULL,
    piso int  NULL,
    depto varchar(50)  NULL,
    tipo varchar(20)  NOT NULL,
    cod_barrio int  NOT NULL,
    cod_ciudad int  NOT NULL,
    CONSTRAINT PK_GR29_DIRECCION PRIMARY KEY (id_direccion)
);

-- Table: GR29_EMPLEADO
CREATE TABLE GR29_EMPLEADO (
    id_persona int  NOT NULL,
    fecha_alta date  NOT NULL,
    CONSTRAINT PK_GR29_EMPLEADO PRIMARY KEY (id_persona)
);

-- Table: GR29_EQUIPO
CREATE TABLE GR29_EQUIPO (
    id_equipo int  NOT NULL,
    nombre varchar(80)  NOT NULL,
    MAC varchar(20)  NULL,
    IP varchar(20)  NULL,
    AP varchar(20)  NULL,
    id_servicio int  NOT NULL,
    id_direccion int  NOT NULL,
    id_persona int  NOT NULL,
    id_carac int  NOT NULL DEFAULT 0,
    mod_conex varchar(10)  NOT NULL,
    asig_ip varchar(10)  NOT NULL,
    CONSTRAINT PK_GR29_EQUIPO PRIMARY KEY (id_equipo)
);

-- Table: GR29_LINEA_COMPROBANTE
CREATE TABLE GR29_LINEA_COMPROBANTE (
    nro_linea int NOT NULL,
    descripcion varchar(80)  NOT NULL,
    cantidad int  NOT NULL,
    importe numeric(18,5)  NOT NULL,
    id_tcomp int  NOT NULL,
    id_comp bigint  NOT NULL,
    CONSTRAINT PK_GR29_LINEA_COMPROBANTE PRIMARY KEY (nro_linea,id_tcomp,id_comp)
);

-- Table: GR29_PERSONA
CREATE TABLE GR29_PERSONA (
    id_persona int  NOT NULL,
    tipodoc char(1)  NOT NULL,
    nrodoc int  NOT NULL,
    nombre varchar(40)  NOT NULL,
    apellido varchar(40)  NOT NULL,
    fecha_nacimiento date  NOT NULL,
    fecha_baja date  NULL,
    password varchar(40)  NULL,
    activo boolean  NOT NULL,
    telefono_caracteristica numeric(3,0)  NOT NULL,
    telefono_numero smallint  NOT NULL,
    telefono_tipo char(1)  NOT NULL,
    mail varchar(120)  NOT NULL,
    calle varchar(50)  NOT NULL,
    numero int  NOT NULL,
    piso_departamento varchar(15)  NOT NULL,
    rol char(1)  NOT NULL,
    cod_ciudad int  NOT NULL,
    CONSTRAINT PK_GR29_PERSONA PRIMARY KEY (id_persona)
);

-- Table: GR29_SERVICIO
CREATE TABLE GR29_SERVICIO (
    id_servicio int  NOT NULL,
    nombre varchar(80)  NOT NULL,
    periodico boolean  NOT NULL,
    costo numeric(18,3)  NOT NULL,
    intervalo int  NULL,
    tipo_intervalo varchar(20)  NULL CHECK (tipo_intervalo in ('semana','quincena','mes','bimestre')),
    activo boolean  NOT NULL DEFAULT true,
    categoria_servicio char(1)  NOT NULL,
    CONSTRAINT PK_GR29_SERVICIO PRIMARY KEY (id_servicio)
);

-- Table: GR29_TIPO_COMPROBANTE
CREATE TABLE GR29_TIPO_COMPROBANTE (
    id_tcomp int  NOT NULL,
    nombre varchar(30)  NOT NULL,
    CONSTRAINT PK_GR29_TIPO_COMPROBANTE PRIMARY KEY (id_tcomp)
);

-- Table: GR29_TURNO
CREATE TABLE GR29_TURNO (
    id_turno int  NOT NULL,
    desde date  NOT NULL,
    hasta date  NULL,
    dinero_inicio numeric(18,3)  NOT NULL,
    dinero_fin numeric(18,3)  NULL,
    id_persona int  NOT NULL,
    cod_lugar int  NOT NULL,
    CONSTRAINT PK_GR29_TURNO PRIMARY KEY (id_turno)
);

-- FOREIGN KEYS

-- Reference: FK_GR29_CLIENTE_GR29_PERSONA (table: GR29_CLIENTE)
ALTER TABLE GR29_CLIENTE ADD CONSTRAINT FK_GR29_CLIENTE_GR29_PERSONA
    FOREIGN KEY (id_persona)
    REFERENCES GR29_PERSONA (id_persona)
    ON DELETE  CASCADE 
    ON UPDATE  CASCADE 
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: FK_GR29_COMPROBANTE_COMPROBANTE_SINL_GR29_COMPROBANTE (table: GR29_COMPROBANTE_SINL)
ALTER TABLE GR29_COMPROBANTE_SINL ADD CONSTRAINT FK_GR29_COMPROBANTE_COMPROBANTE_SINL_GR29_COMPROBANTE
    FOREIGN KEY (id_tcomp, id_comp)
    REFERENCES GR29_COMPROBANTE (id_tcomp, id_comp)
    ON DELETE  CASCADE 
    ON UPDATE  CASCADE 
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: FK_GR29_COMPROBANTE_CONL_GR29_CLIENTE (table: GR29_COMPROBANTE_CONL)
ALTER TABLE GR29_COMPROBANTE_CONL ADD CONSTRAINT FK_GR29_COMPROBANTE_CONL_GR29_CLIENTE
    FOREIGN KEY (id_persona)
    REFERENCES GR29_CLIENTE (id_persona)
    ON DELETE  CASCADE 
    ON UPDATE  CASCADE 
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: FK_GR29_COMPROBANTE_CONL_GR29_COMPROBANTE_CONL (table: GR29_COMPROBANTE_CONL)
ALTER TABLE GR29_COMPROBANTE_CONL ADD CONSTRAINT FK_GR29_COMPROBANTE_CONL_GR29_COMPROBANTE_CONL
    FOREIGN KEY (id_tcomp, id_comp)
    REFERENCES GR29_COMPROBANTE (id_tcomp, id_comp)
    ON DELETE  CASCADE 
    ON UPDATE  CASCADE 
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: FK_GR29_COMPROBANTE_CONL_LINEA_COMPROBANTE (table: GR29_LINEA_COMPROBANTE)
ALTER TABLE GR29_LINEA_COMPROBANTE ADD CONSTRAINT FK_GR29_COMPROBANTE_CONL_LINEA_COMPROBANTE
    FOREIGN KEY (id_tcomp, id_comp)
    REFERENCES GR29_COMPROBANTE_CONL (id_tcomp, id_comp)
    ON DELETE  CASCADE 
    ON UPDATE  CASCADE 
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: FK_GR29_COMPROBANTE_SINL_GR29_TURNO (table: GR29_COMPROBANTE_SINL)
ALTER TABLE GR29_COMPROBANTE_SINL ADD CONSTRAINT FK_GR29_COMPROBANTE_SINL_GR29_TURNO
    FOREIGN KEY (id_turno)
    REFERENCES GR29_TURNO (id_turno)
    ON DELETE  SET NULL 
    ON UPDATE  CASCADE 
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: FK_GR29_COMPROBANTE_SINL_TURNO_GR29_CLIENTE (table: GR29_COMPROBANTE_SINL_TURNO)
ALTER TABLE GR29_COMPROBANTE_SINL_TURNO ADD CONSTRAINT FK_GR29_COMPROBANTE_SINL_TURNO_GR29_CLIENTE
    FOREIGN KEY (id_persona)
    REFERENCES GR29_CLIENTE (id_persona)
    ON DELETE  CASCADE 
    ON UPDATE  CASCADE 
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: FK_GR29_COMPROBANTE_SINL_TURNO_GR29_COMPROBANTE (table: GR29_COMPROBANTE_SINL_TURNO)
ALTER TABLE GR29_COMPROBANTE_SINL_TURNO ADD CONSTRAINT FK_GR29_COMPROBANTE_SINL_TURNO_GR29_COMPROBANTE
    FOREIGN KEY (id_tcomp, id_comp)
    REFERENCES GR29_COMPROBANTE (id_tcomp, id_comp)
    ON DELETE  CASCADE 
    ON UPDATE  CASCADE 
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: FK_GR29_COMPROBANTE_SINL_TURNO_GR29_TURNO (table: GR29_COMPROBANTE_SINL_TURNO)
ALTER TABLE GR29_COMPROBANTE_SINL_TURNO ADD CONSTRAINT FK_GR29_COMPROBANTE_SINL_TURNO_GR29_TURNO
    FOREIGN KEY (id_turno)
    REFERENCES GR29_TURNO (id_turno)
    ON DELETE  CASCADE 
    ON UPDATE  CASCADE 
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: FK_GR29_EMPLEADO_GR29_PERSONA (table: GR29_EMPLEADO)
ALTER TABLE GR29_EMPLEADO ADD CONSTRAINT FK_GR29_EMPLEADO_GR29_PERSONA
    FOREIGN KEY (id_persona)
    REFERENCES GR29_PERSONA (id_persona)
    ON DELETE  CASCADE 
    ON UPDATE  CASCADE 
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: FK_GR29_EQUIPO_GR29_CLIENTE (table: GR29_EQUIPO)
ALTER TABLE GR29_EQUIPO ADD CONSTRAINT FK_GR29_EQUIPO_GR29_CLIENTE
    FOREIGN KEY (id_persona)
    REFERENCES GR29_CLIENTE (id_persona)
    ON DELETE  SET NULL 
    ON UPDATE  CASCADE 
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: FK_GR29_EQUIPO_GR29_DIRECCION (table: GR29_EQUIPO)
ALTER TABLE GR29_EQUIPO ADD CONSTRAINT FK_GR29_EQUIPO_GR29_DIRECCION
    FOREIGN KEY (id_direccion)
    REFERENCES GR29_DIRECCION (id_direccion)
    ON DELETE  SET NULL 
    ON UPDATE  CASCADE 
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: FK_GR29_EQUIPO_GR29_EQUIPO_CARAC (table: GR29_EQUIPO)
ALTER TABLE GR29_EQUIPO ADD CONSTRAINT FK_GR29_EQUIPO_GR29_EQUIPO_CARAC
    FOREIGN KEY (id_carac)
    REFERENCES GR29_CARAC_EQUIPO (id_carac)
    ON DELETE  SET DEFAULT 
    ON UPDATE  CASCADE 
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: FK_GR29_EQUIPO_GR29_SERVICIO (table: GR29_EQUIPO)
ALTER TABLE GR29_EQUIPO ADD CONSTRAINT FK_GR29_EQUIPO_GR29_SERVICIO
    FOREIGN KEY (id_servicio)
    REFERENCES GR29_SERVICIO (id_servicio)
    ON DELETE  SET NULL 
    ON UPDATE  CASCADE 
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: FK_GR29_GR29_COMPROBANTE_GR29_TIPO_COMPROBANTE (table: GR29_COMPROBANTE)
ALTER TABLE GR29_COMPROBANTE ADD CONSTRAINT FK_GR29_GR29_COMPROBANTE_GR29_TIPO_COMPROBANTE
    FOREIGN KEY (id_tcomp)
    REFERENCES GR29_TIPO_COMPROBANTE (id_tcomp)
    ON DELETE  SET NULL 
    ON UPDATE  CASCADE 
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: FK_GR29_TURNO_GR29_EMPLEADO (table: GR29_TURNO)
ALTER TABLE GR29_TURNO ADD CONSTRAINT FK_GR29_TURNO_GR29_EMPLEADO
    FOREIGN KEY (id_persona)
    REFERENCES GR29_EMPLEADO (id_persona)
    ON DELETE  SET NULL 
    ON UPDATE  CASCADE 
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

--SEQUENCE

--Secuencia para los identificadores de los comprobantes Facturas(0)--
CREATE SEQUENCE GR29_SEQ_id_comp INCREMENT BY 1
MINVALUE 0 NO MAXVALUE
START 0 NO CYCLE
;

--Secuencia para los identificadores de los comprobantes Debito(1)--
CREATE SEQUENCE GR29_SEQ_id_comp_Debs INCREMENT BY 1
MINVALUE 0 NO MAXVALUE
START 0 NO CYCLE
;

--Secuencia para los identificadores de los comprobantes Remitos(2)--
CREATE SEQUENCE GR29_SEQ_id_comp_Rems INCREMENT BY 1
MINVALUE 0 NO MAXVALUE
START 0 NO CYCLE
;
-- End of file.

